<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyVersion>26.1.68.0</AssemblyVersion>
    <FileVersion>26.1.68.0</FileVersion>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Syncfusion.Licensing" Version="32.1.23" />
    <PackageReference Include="Syncfusion.Pdf.Wpf" Version="32.1.23" />
    <PackageReference Include="Syncfusion.SfGrid.WPF" Version="32.1.23" />
    <PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="32.1.23" />
    <PackageReference Include="Syncfusion.Themes.Windows11Dark.WPF" Version="32.1.23" />
    <PackageReference Include="Syncfusion.Themes.Windows11Light.WPF" Version="32.1.23" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Config\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Config\licentieovereenkomst.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Config\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Config\MySqlAnalyzer.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
